// Auto-generated by Supabase MCP `generate_typescript_types` (2026-05-01).
//
// To regenerate after a schema change:
//   1. Land the migration via deploy-migrations workflow on the racing repo
//   2. Re-run generate_typescript_types via Supabase MCP
//   3. Replace the body of this file with the fresh output
//
// Do not edit by hand — manual edits will be lost on the next regeneration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      daily_leaderboard: {
        Row: {
          best_distance: number | null
          best_score: number
          created_at: string | null
          full_wallet: string | null
          games_played_today: number | null
          id: string
          play_date: string
          wallet_address: string
        }
        Insert: {
          best_distance?: number | null
          best_score?: number
          created_at?: string | null
          full_wallet?: string | null
          games_played_today?: number | null
          id?: string
          play_date?: string
          wallet_address: string
        }
        Update: {
          best_distance?: number | null
          best_score?: number
          created_at?: string | null
          full_wallet?: string | null
          games_played_today?: number | null
          id?: string
          play_date?: string
          wallet_address?: string
        }
        Relationships: []
      }
      daily_leaderboard_history: {
        Row: {
          archived_at: string | null
          best_distance: number | null
          best_score: number
          full_wallet: string | null
          games_played_today: number | null
          id: string
          play_date: string
          wallet_address: string
        }
        Insert: {
          archived_at?: string | null
          best_distance?: number | null
          best_score: number
          full_wallet?: string | null
          games_played_today?: number | null
          id?: string
          play_date: string
          wallet_address: string
        }
        Update: {
          archived_at?: string | null
          best_distance?: number | null
          best_score?: number
          full_wallet?: string | null
          games_played_today?: number | null
          id?: string
          play_date?: string
          wallet_address?: string
        }
        Relationships: []
      }
      leaderboard_history: {
        Row: {
          id: number
          rank: number | null
          score: number | null
          wallet_address: string | null
          won_at: string | null
        }
        Insert: {
          id?: number
          rank?: number | null
          score?: number | null
          wallet_address?: string | null
          won_at?: string | null
        }
        Update: {
          id?: number
          rank?: number | null
          score?: number | null
          wallet_address?: string | null
          won_at?: string | null
        }
        Relationships: []
      }
      rate_limits: {
        Row: {
          action: string
          key: string
          request_count: number
          window_start: string
        }
        Insert: {
          action: string
          key: string
          request_count?: number
          window_start?: string
        }
        Update: {
          action?: string
          key?: string
          request_count?: number
          window_start?: string
        }
        Relationships: []
      }
      reward_pool_distribution: {
        Row: {
          created_at: string
          id: string
          reward_amount: number
          reward_date: string
          score: number
          wallet_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          reward_amount: number
          reward_date?: string
          score: number
          wallet_id: string
        }
        Update: {
          created_at?: string
          id?: string
          reward_amount?: number
          reward_date?: string
          score?: number
          wallet_id?: string
        }
        Relationships: []
      }
      scores: {
        Row: {
          coins_collected: number | null
          created_at: string | null
          distance: number
          duration: number | null
          game_mode: string | null
          id: string
          play_duration: number | null
          score: number
          team: string | null
          user_id: string | null
          wallet_address: string
        }
        Insert: {
          coins_collected?: number | null
          created_at?: string | null
          distance: number
          duration?: number | null
          game_mode?: string | null
          id?: string
          play_duration?: number | null
          score: number
          team?: string | null
          user_id?: string | null
          wallet_address: string
        }
        Update: {
          coins_collected?: number | null
          created_at?: string | null
          distance?: number
          duration?: number | null
          game_mode?: string | null
          id?: string
          play_duration?: number | null
          score?: number
          team?: string | null
          user_id?: string | null
          wallet_address?: string
        }
        Relationships: [
          {
            foreignKeyName: "scores_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      suspicious_scores: {
        Row: {
          coins_collected: number
          created_at: string
          distance: number
          duration: number
          game_mode: string | null
          id: string
          near_miss_count: number | null
          payload: Json | null
          reasons: string[]
          score: number
          wallet_address: string
        }
        Insert: {
          coins_collected: number
          created_at?: string
          distance: number
          duration: number
          game_mode?: string | null
          id?: string
          near_miss_count?: number | null
          payload?: Json | null
          reasons: string[]
          score: number
          wallet_address: string
        }
        Update: {
          coins_collected?: number
          created_at?: string
          distance?: number
          duration?: number
          game_mode?: string | null
          id?: string
          near_miss_count?: number | null
          payload?: Json | null
          reasons?: string[]
          score?: number
          wallet_address?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
          amount: number
          created_at: string | null
          credits_added: number
          id: string
          status: string | null
          token_amount: number | null
          token_symbol: string | null
          transaction_hash: string
          user_id: string | null
        }
        Insert: {
          amount: number
          created_at?: string | null
          credits_added: number
          id?: string
          status?: string | null
          token_amount?: number | null
          token_symbol?: string | null
          transaction_hash: string
          user_id?: string | null
        }
        Update: {
          amount?: number
          created_at?: string | null
          credits_added?: number
          id?: string
          status?: string | null
          token_amount?: number | null
          token_symbol?: string | null
          transaction_hash?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "transactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          best_score: number | null
          created_at: string | null
          credits: number | null
          id: string
          last_played: string | null
          selected_team: string | null
          team_selection_date: string | null
          total_games: number | null
          total_games_played: number | null
          total_spent: number | null
          updated_at: string | null
          wallet_address: string
        }
        Insert: {
          best_score?: number | null
          created_at?: string | null
          credits?: number | null
          id?: string
          last_played?: string | null
          selected_team?: string | null
          team_selection_date?: string | null
          total_games?: number | null
          total_games_played?: number | null
          total_spent?: number | null
          updated_at?: string | null
          wallet_address: string
        }
        Update: {
          best_score?: number | null
          created_at?: string | null
          credits?: number | null
          id?: string
          last_played?: string | null
          selected_team?: string | null
          team_selection_date?: string | null
          total_games?: number | null
          total_games_played?: number | null
          total_spent?: number | null
          updated_at?: string | null
          wallet_address?: string
        }
        Relationships: []
      }
    }
    Views: {
      alltime_leaderboard: {
        Row: {
          avg_score: number | null
          best_distance: number | null
          best_score: number | null
          total_games: number | null
          total_games_played: number | null
          total_spent: number | null
          wallet_address: string | null
        }
        Relationships: []
      }
      daily_team_scores: {
        Row: {
          avg_score: number | null
          best_score: number | null
          play_date: string | null
          team: string | null
          total_games: number | null
          total_score: number | null
          unique_players: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      archive_daily_leaderboard: { Args: never; Returns: Json }
      check_rate_limit: {
        Args: {
          p_action: string
          p_key: string
          p_max_requests: number
          p_window_seconds: number
        }
        Returns: boolean
      }
      cleanup_rate_limits: {
        Args: { p_keep_seconds?: number }
        Returns: number
      }
      distribute_daily_team_bonus: {
        Args: { target_date?: string }
        Returns: {
          bonus_credits: number
          result: string
          team: string
          wallet_address: string
        }[]
      }
      end_the_day: { Args: never; Returns: undefined }
      submit_score: {
        Args: {
          p_coins?: number
          p_distance: number
          p_duration: number
          p_score: number
          p_wallet: string
        }
        Returns: Json
      }
      update_team_selection: {
        Args: { p_team: string; p_wallet_address: string }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
